"""add applicant_fit_scores

Revision ID: 38a34434c2d1
Revises: b8d4f2a1c3e5
Create Date: 2026-04-30 20:29:32.589329
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

revision: str = '38a34434c2d1'
down_revision: Union[str, None] = 'b8d4f2a1c3e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicant_fit_scores',
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'ranking', 'done', 'failed', 'skipped', name='rankstatus'), nullable=False),
    sa.Column('fit_score', sa.Integer(), nullable=True),
    sa.Column('skills_match', sa.Integer(), nullable=True),
    sa.Column('experience_match', sa.Integer(), nullable=True),
    sa.Column('trajectory', sa.Integer(), nullable=True),
    sa.Column('reasoning', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.PrimaryKeyConstraint('applicant_id')
    )
    op.create_index(op.f('ix_applicant_fit_scores_fit_score'), 'applicant_fit_scores', ['fit_score'], unique=False)
    op.create_index(op.f('ix_applicant_fit_scores_status'), 'applicant_fit_scores', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applicant_fit_scores_status'), table_name='applicant_fit_scores')
    op.drop_index(op.f('ix_applicant_fit_scores_fit_score'), table_name='applicant_fit_scores')
    op.drop_table('applicant_fit_scores')
    # ### end Alembic commands ###
