"""initial

Revision ID: e67ca1c9c30d
Revises: 
Create Date: 2026-04-27 23:33:34.003924
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'e67ca1c9c30d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('role', sa.Enum('admin', 'reviewer', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('jobs',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description_md', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'closed', name='jobstatus'), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_slug'), 'jobs', ['slug'], unique=True)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('template_assessment_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('question_text', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('max_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_assessment_questions_template_id'), 'template_assessment_questions', ['template_id'], unique=False)
    op.create_table('template_form_fields',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('field_type', sa.Enum('text', 'textarea', 'email', 'url', 'number', 'file', 'dropdown', 'checkbox', name='fieldtype'), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_form_fields_template_id'), 'template_form_fields', ['template_id'], unique=False)
    op.create_table('job_assessment_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('question_text', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('max_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_assessment_questions_job_id'), 'job_assessment_questions', ['job_id'], unique=False)
    op.create_table('job_form_fields',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('field_type', sa.Enum('text', 'textarea', 'email', 'url', 'number', 'file', 'dropdown', 'checkbox', name='fieldtype'), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_form_fields_job_id'), 'job_form_fields', ['job_id'], unique=False)
    op.create_table('pipeline_stages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_stages_job_id'), 'pipeline_stages', ['job_id'], unique=False)
    op.create_table('applicants',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('current_stage_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('resume_gcs_path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('parse_status', sa.Enum('pending', 'parsing', 'parsed', 'failed', 'needs_manual', name='parsestatus'), nullable=False),
    sa.Column('parse_error', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('parse_attempts', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_stage_id'], ['pipeline_stages.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'email', name='uq_applicants_job_email')
    )
    op.create_index(op.f('ix_applicants_current_stage_id'), 'applicants', ['current_stage_id'], unique=False)
    op.create_index(op.f('ix_applicants_email'), 'applicants', ['email'], unique=False)
    op.create_index(op.f('ix_applicants_job_id'), 'applicants', ['job_id'], unique=False)
    op.create_index(op.f('ix_applicants_parse_status'), 'applicants', ['parse_status'], unique=False)
    op.create_table('job_integrations',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('stage_id', sa.Uuid(), nullable=False),
    sa.Column('endpoint_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('api_key_encrypted', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('include_assessment', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['pipeline_stages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'stage_id', name='uq_job_integration_job_stage')
    )
    op.create_index(op.f('ix_job_integrations_job_id'), 'job_integrations', ['job_id'], unique=False)
    op.create_table('applicant_custom_field_values',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('job_form_field_id', sa.Uuid(), nullable=False),
    sa.Column('value_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('value_file_gcs_path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.ForeignKeyConstraint(['job_form_field_id'], ['job_form_fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applicant_custom_field_values_applicant_id'), 'applicant_custom_field_values', ['applicant_id'], unique=False)
    op.create_table('applicant_education',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('institution', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('degree', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('field_of_study', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applicant_education_applicant_id'), 'applicant_education', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_applicant_education_degree'), 'applicant_education', ['degree'], unique=False)
    op.create_index(op.f('ix_applicant_education_institution'), 'applicant_education', ['institution'], unique=False)
    op.create_table('applicant_notes',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applicant_notes_applicant_id'), 'applicant_notes', ['applicant_id'], unique=False)
    op.create_table('applicant_skills',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('skill', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applicant_skills_applicant_id'), 'applicant_skills', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_applicant_skills_skill'), 'applicant_skills', ['skill'], unique=False)
    op.create_table('applicant_work',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('end_date', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applicant_work_applicant_id'), 'applicant_work', ['applicant_id'], unique=False)
    op.create_table('parsed_resumes',
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('top_institution', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('top_degree', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.Column('confidence_notes', sa.JSON(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.PrimaryKeyConstraint('applicant_id')
    )
    op.create_index(op.f('ix_parsed_resumes_top_degree'), 'parsed_resumes', ['top_degree'], unique=False)
    op.create_index(op.f('ix_parsed_resumes_top_institution'), 'parsed_resumes', ['top_institution'], unique=False)
    op.create_table('stage_transitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('from_stage_id', sa.Uuid(), nullable=True),
    sa.Column('to_stage_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.ForeignKeyConstraint(['from_stage_id'], ['pipeline_stages.id'], ),
    sa.ForeignKeyConstraint(['to_stage_id'], ['pipeline_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_transitions_applicant_id'), 'stage_transitions', ['applicant_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transition_id', sa.Uuid(), nullable=False),
    sa.Column('integration_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('is_manual_retry', sa.Boolean(), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['job_integrations.id'], ),
    sa.ForeignKeyConstraint(['transition_id'], ['stage_transitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transition_id', 'integration_id', 'attempt_number', name='uq_webhook_delivery_idempotency')
    )
    op.create_index(op.f('ix_webhook_deliveries_integration_id'), 'webhook_deliveries', ['integration_id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_transition_id'), 'webhook_deliveries', ['transition_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_deliveries_transition_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_integration_id'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_stage_transitions_applicant_id'), table_name='stage_transitions')
    op.drop_table('stage_transitions')
    op.drop_index(op.f('ix_parsed_resumes_top_institution'), table_name='parsed_resumes')
    op.drop_index(op.f('ix_parsed_resumes_top_degree'), table_name='parsed_resumes')
    op.drop_table('parsed_resumes')
    op.drop_index(op.f('ix_applicant_work_applicant_id'), table_name='applicant_work')
    op.drop_table('applicant_work')
    op.drop_index(op.f('ix_applicant_skills_skill'), table_name='applicant_skills')
    op.drop_index(op.f('ix_applicant_skills_applicant_id'), table_name='applicant_skills')
    op.drop_table('applicant_skills')
    op.drop_index(op.f('ix_applicant_notes_applicant_id'), table_name='applicant_notes')
    op.drop_table('applicant_notes')
    op.drop_index(op.f('ix_applicant_education_institution'), table_name='applicant_education')
    op.drop_index(op.f('ix_applicant_education_degree'), table_name='applicant_education')
    op.drop_index(op.f('ix_applicant_education_applicant_id'), table_name='applicant_education')
    op.drop_table('applicant_education')
    op.drop_index(op.f('ix_applicant_custom_field_values_applicant_id'), table_name='applicant_custom_field_values')
    op.drop_table('applicant_custom_field_values')
    op.drop_index(op.f('ix_job_integrations_job_id'), table_name='job_integrations')
    op.drop_table('job_integrations')
    op.drop_index(op.f('ix_applicants_parse_status'), table_name='applicants')
    op.drop_index(op.f('ix_applicants_job_id'), table_name='applicants')
    op.drop_index(op.f('ix_applicants_email'), table_name='applicants')
    op.drop_index(op.f('ix_applicants_current_stage_id'), table_name='applicants')
    op.drop_table('applicants')
    op.drop_index(op.f('ix_pipeline_stages_job_id'), table_name='pipeline_stages')
    op.drop_table('pipeline_stages')
    op.drop_index(op.f('ix_job_form_fields_job_id'), table_name='job_form_fields')
    op.drop_table('job_form_fields')
    op.drop_index(op.f('ix_job_assessment_questions_job_id'), table_name='job_assessment_questions')
    op.drop_table('job_assessment_questions')
    op.drop_index(op.f('ix_template_form_fields_template_id'), table_name='template_form_fields')
    op.drop_table('template_form_fields')
    op.drop_index(op.f('ix_template_assessment_questions_template_id'), table_name='template_assessment_questions')
    op.drop_table('template_assessment_questions')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_slug'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('templates')
    # ### end Alembic commands ###
